# Generated by Django 5.0.3 on 2024-03-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_movie_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='row_count',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='seat_count',
        ),
        migrations.AddField(
            model_name='room',
            name='row_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='seat_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
