# Generated by Django 5.0.3 on 2024-03-15 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_remove_schedule_row_count_remove_schedule_seat_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(null=True, verbose_name='Please write duration of movie with in minute'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('row_index', models.PositiveIntegerField()),
                ('seat_index', models.PositiveIntegerField()),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema.schedule')),
            ],
        ),
    ]
